/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.Car;
import model.CarFleet;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;

/**
 *
 * @author karpe.s@northeastern.edu
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    CarFleet carFleetDetails;
    public boolean isValid = false;
    public boolean isFormValid = false;
            
    public CreateJPanel(CarFleet carFleetDetails) {
        initComponents();
        this.carFleetDetails = carFleetDetails;
        btnSave.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTitle = new javax.swing.JLabel();
        modelNumLabel = new javax.swing.JLabel();
        serialNumLabel = new javax.swing.JLabel();
        madeByLabel = new javax.swing.JLabel();
        lblManufacturedDate = new javax.swing.JLabel();
        seatAvailLable = new javax.swing.JLabel();
        usedByLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        certExpireLabel = new javax.swing.JLabel();
        txtModelNum = new javax.swing.JTextField();
        txtSerialNum = new javax.swing.JTextField();
        txtManufacturedDate = new javax.swing.JTextField();
        txtSeatCapacity = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtMaintenanceCertExpDate = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        isAvailableLabel = new javax.swing.JLabel();
        chkboxAvailable = new java.awt.Checkbox();
        appBox = new javax.swing.JComboBox<>();
        lblTitleSubHeading = new javax.swing.JLabel();
        comboBoxManufacturerCreate = new javax.swing.JComboBox<>();
        lblManuDateErrMsg = new javax.swing.JLabel();
        lblMaintDateExpErrMsg = new javax.swing.JLabel();
        lblModelNumErrMsg = new javax.swing.JLabel();
        lblSerialNumErrMsg = new javax.swing.JLabel();
        lblSeatCapacityErrMsg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(214, 238, 255));

        btnTitle.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTitle.setText("Enter Car Details");
        btnTitle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modelNumLabel.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        modelNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modelNumLabel.setText("Model Number");
        modelNumLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        serialNumLabel.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        serialNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serialNumLabel.setText("Serial Number");
        serialNumLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        madeByLabel.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        madeByLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        madeByLabel.setText("Car Model");
        madeByLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblManufacturedDate.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblManufacturedDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManufacturedDate.setText("Manufactured On");
        lblManufacturedDate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        seatAvailLable.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        seatAvailLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seatAvailLable.setText("Number of Seats Available");
        seatAvailLable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        usedByLabel.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        usedByLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usedByLabel.setText("Available on App");
        usedByLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cityLabel.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        cityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cityLabel.setText("City");
        cityLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        certExpireLabel.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        certExpireLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        certExpireLabel.setText("Certificate Expire Date");
        certExpireLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtModelNum.setToolTipText("Only accepts numeric value");
        txtModelNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtModelNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNumActionPerformed(evt);
            }
        });
        txtModelNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtModelNumKeyPressed(evt);
            }
        });

        txtSerialNum.setToolTipText("Only accepts numeric value");
        txtSerialNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSerialNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumActionPerformed(evt);
            }
        });
        txtSerialNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSerialNumKeyPressed(evt);
            }
        });

        txtManufacturedDate.setToolTipText("Enter Date as MM/dd/yyyy");
        txtManufacturedDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtManufacturedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturedDateActionPerformed(evt);
            }
        });
        txtManufacturedDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtManufacturedDateKeyPressed(evt);
            }
        });

        txtSeatCapacity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSeatCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatCapacityActionPerformed(evt);
            }
        });
        txtSeatCapacity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSeatCapacityKeyPressed(evt);
            }
        });

        txtCity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCityKeyPressed(evt);
            }
        });

        txtMaintenanceCertExpDate.setToolTipText("Enter Date as MM/dd/yyyy");
        txtMaintenanceCertExpDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMaintenanceCertExpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaintenanceCertExpDateActionPerformed(evt);
            }
        });
        txtMaintenanceCertExpDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaintenanceCertExpDateKeyPressed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setText("OK");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        isAvailableLabel.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        isAvailableLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isAvailableLabel.setText("Car Availability");
        isAvailableLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        chkboxAvailable.setLabel("Is Available");

        appBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uber", "Lyft", "Ola", "All" }));
        appBox.setSelectedIndex(-1);
        appBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appBoxActionPerformed(evt);
            }
        });

        lblTitleSubHeading.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblTitleSubHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleSubHeading.setText("Fill all Mandatory fields (Marked Bold)");

        comboBoxManufacturerCreate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Honda", "Volkswagen", "Ford Motor Co.", "Tata Motors", "General Motors" }));
        comboBoxManufacturerCreate.setSelectedIndex(-1);
        comboBoxManufacturerCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxManufacturerCreateActionPerformed(evt);
            }
        });

        lblManuDateErrMsg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMaintDateExpErrMsg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblModelNumErrMsg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSerialNumErrMsg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSeatCapacityErrMsg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblManufacturedDate)
                    .addComponent(serialNumLabel)
                    .addComponent(modelNumLabel)
                    .addComponent(madeByLabel)
                    .addComponent(seatAvailLable)
                    .addComponent(usedByLabel)
                    .addComponent(cityLabel)
                    .addComponent(certExpireLabel)
                    .addComponent(isAvailableLabel))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMaintenanceCertExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMaintDateExpErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkboxAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(91, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSerialNum)
                                .addGap(18, 18, 18)
                                .addComponent(lblSerialNumErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtModelNum)
                                .addGap(18, 18, 18)
                                .addComponent(lblModelNumErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(appBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSeatCapacity)
                                .addGap(18, 18, 18)
                                .addComponent(lblSeatCapacityErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtManufacturedDate)
                                .addGap(18, 18, 18)
                                .addComponent(lblManuDateErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboBoxManufacturerCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 91, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(lblTitleSubHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCity, txtManufacturedDate, txtModelNum, txtSeatCapacity, txtSerialNum});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {certExpireLabel, cityLabel, isAvailableLabel, lblManufacturedDate, madeByLabel, modelNumLabel, seatAvailLable, serialNumLabel, usedByLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTitle)
                        .addGap(3, 3, 3)
                        .addComponent(lblTitleSubHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelNumLabel)
                            .addComponent(txtModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModelNumErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serialNumLabel)
                            .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblSerialNumErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(madeByLabel)
                    .addComponent(comboBoxManufacturerCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManufacturedDate)
                            .addComponent(txtManufacturedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManuDateErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seatAvailLable)
                            .addComponent(txtSeatCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblSeatCapacityErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usedByLabel)
                    .addComponent(appBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(certExpireLabel)
                        .addComponent(txtMaintenanceCertExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMaintDateExpErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkboxAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isAvailableLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(38, 38, 38))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {appBox, certExpireLabel, cityLabel, comboBoxManufacturerCreate, isAvailableLabel, lblManufacturedDate, madeByLabel, modelNumLabel, seatAvailLable, serialNumLabel, txtCity, txtMaintenanceCertExpDate, txtManufacturedDate, txtModelNum, txtSeatCapacity, txtSerialNum, usedByLabel});

    }// </editor-fold>//GEN-END:initComponents

    private void txtModelNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNumActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        if (!txtManufacturedDate.getText().isEmpty()) {
           try
            {
                formatter.parse(txtManufacturedDate.getText());
                lblManuDateErrMsg.setText("");
                isFormValid = true;
            }

            catch (Exception e)
            {
                lblManuDateErrMsg.setText("Date Format is Invalid");
                isFormValid = false;
            } 
        }
        if (!txtMaintenanceCertExpDate.getText().isEmpty()) {
           try
            {
                formatter.parse(txtMaintenanceCertExpDate.getText());
                lblMaintDateExpErrMsg.setText("");
                isFormValid = true;
            }

            catch (Exception e)
            {
                lblMaintDateExpErrMsg.setText("Date Format is Invalid");
                isFormValid = false;
            } 
        }
        if (isFormValid) {
          DateTimeFormatter dformatter = DateTimeFormatter.ofPattern("MM/dd/yyyy");
            LocalDate localDate = LocalDate.parse(txtManufacturedDate.getText(), dformatter);
            LocalDate localDateCertExpire = LocalDate.parse(txtMaintenanceCertExpDate.getText(), dformatter);
            LocalDate todaysDate = LocalDate.now();
            int modelNumber = Integer.parseInt(txtModelNum.getText());
            int serialNumber = Integer.parseInt(txtSerialNum.getText());  
            Object createdManufacturer = comboBoxManufacturerCreate.getSelectedItem();
            String manufacturer = createdManufacturer.toString();
            LocalDate manufacturedDate = localDate;
            int seatCapacity = Integer.parseInt(txtSeatCapacity.getText());
            Object createdUsedByApp = appBox.getSelectedItem();
            String usedBy = createdUsedByApp.toString();
            LocalDate lastUpdated = todaysDate;
            String city = txtCity.getText();
            LocalDate maintenanceCertExpDate = localDateCertExpire;
            Boolean IsAvailable = chkboxAvailable.getState();

            Car c = carFleetDetails.addNewCar();

            c.setModelNumber(modelNumber);
            c.setSerialNumber(serialNumber);
            c.setManufacturer(manufacturer);
            c.setManufacturedDate(manufacturedDate);
            c.setSeatCapacity(seatCapacity);
            c.setUsedByApp(usedBy);
            c.setIsAvailable(IsAvailable);
            c.setLastUpdated(lastUpdated);
            c.setCity(city);
            c.setMaintenanceCertExpDate(maintenanceCertExpDate);

            JOptionPane.showMessageDialog(this, "New Car Record Added");

            txtModelNum.setText("");
            txtSerialNum.setText("");
            comboBoxManufacturerCreate.setSelectedIndex(-1);
            txtManufacturedDate.setText("");
            txtSeatCapacity.setText("");
            appBox.setSelectedIndex(-1);
            txtCity.setText("");
            txtMaintenanceCertExpDate.setText("");
            chkboxAvailable.setState(false);  
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSerialNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumActionPerformed

    }//GEN-LAST:event_txtSerialNumActionPerformed

    private void txtManufacturedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturedDateActionPerformed
        
    }//GEN-LAST:event_txtManufacturedDateActionPerformed

    private void txtSeatCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatCapacityActionPerformed
        
    }//GEN-LAST:event_txtSeatCapacityActionPerformed

    private void appBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appBoxActionPerformed
        validateMandatory();
    }//GEN-LAST:event_appBoxActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtMaintenanceCertExpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaintenanceCertExpDateActionPerformed
        
    }//GEN-LAST:event_txtMaintenanceCertExpDateActionPerformed

    private void txtModelNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModelNumKeyPressed
        // TODO add your handling code here:
        validateMandatory();
        char NumPressed = evt.getKeyChar();
        if(Character.isLetter(NumPressed)){
            isFormValid = false;
            txtModelNum.setEditable(false);
            lblModelNumErrMsg.setText("Please enter number Only!");
            validateMandatory();
        }
        else
        {
            txtModelNum.setEditable(true);
            isFormValid = true;
            lblModelNumErrMsg.setText("");
            validateMandatory();
        }
    }//GEN-LAST:event_txtModelNumKeyPressed

    private void txtSerialNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialNumKeyPressed
        validateMandatory();
        char NumPressed = evt.getKeyChar();
        if(Character.isLetter(NumPressed)){
            isFormValid = false;
            txtSerialNum.setEditable(false);
            lblSerialNumErrMsg.setText("Please enter number Only!");
            validateMandatory();
        }
        else
        {
            txtSerialNum.setEditable(true);
            isFormValid = true;
            lblSerialNumErrMsg.setText("");
            validateMandatory();
        }
    }//GEN-LAST:event_txtSerialNumKeyPressed

    private void comboBoxManufacturerCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxManufacturerCreateActionPerformed
        // TODO add your handling code here:
        validateMandatory();
    }//GEN-LAST:event_comboBoxManufacturerCreateActionPerformed

    private void txtSeatCapacityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeatCapacityKeyPressed
        validateMandatory();
        char NumPressed = evt.getKeyChar();
        if(Character.isLetter(NumPressed)){
            isFormValid = false;
            txtSeatCapacity.setEditable(false);
            lblSeatCapacityErrMsg.setText("Please enter number Only!");
            validateMandatory();
        }
        else
        {
            txtSeatCapacity.setEditable(true);
            isFormValid = true;
            lblSeatCapacityErrMsg.setText("");
            validateMandatory();
        }
    }//GEN-LAST:event_txtSeatCapacityKeyPressed

    private void txtManufacturedDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManufacturedDateKeyPressed
        validateMandatory();
    }//GEN-LAST:event_txtManufacturedDateKeyPressed

    private void txtCityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyPressed
        validateMandatory();
    }//GEN-LAST:event_txtCityKeyPressed

    private void txtMaintenanceCertExpDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaintenanceCertExpDateKeyPressed
        validateMandatory();
    }//GEN-LAST:event_txtMaintenanceCertExpDateKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> appBox;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel btnTitle;
    private javax.swing.JLabel certExpireLabel;
    private java.awt.Checkbox chkboxAvailable;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JComboBox<String> comboBoxManufacturerCreate;
    private javax.swing.JLabel isAvailableLabel;
    private javax.swing.JLabel lblMaintDateExpErrMsg;
    private javax.swing.JLabel lblManuDateErrMsg;
    private javax.swing.JLabel lblManufacturedDate;
    private javax.swing.JLabel lblModelNumErrMsg;
    private javax.swing.JLabel lblSeatCapacityErrMsg;
    private javax.swing.JLabel lblSerialNumErrMsg;
    private javax.swing.JLabel lblTitleSubHeading;
    private javax.swing.JLabel madeByLabel;
    private javax.swing.JLabel modelNumLabel;
    private javax.swing.JLabel seatAvailLable;
    private javax.swing.JLabel serialNumLabel;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtMaintenanceCertExpDate;
    private javax.swing.JTextField txtManufacturedDate;
    private javax.swing.JTextField txtModelNum;
    private javax.swing.JTextField txtSeatCapacity;
    private javax.swing.JTextField txtSerialNum;
    private javax.swing.JLabel usedByLabel;
    // End of variables declaration//GEN-END:variables

    private void validateMandatory() {
        if (!txtModelNum.getText().isEmpty() && !txtSerialNum.getText().isEmpty()) {
            isValid = true;
            btnSave.setEnabled(isValid);
            return;
        }
    }
}
