/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CarFleet;
import model.Car;
/**
 *
 * @author karpe.s@northeastern.edu
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    CarFleet carFleetDetails;
    public ViewJPanel(CarFleet carFleetDetails) {
        initComponents();
        
        this.carFleetDetails = carFleetDetails;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewCarDetails = new javax.swing.JTable();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        viewDetailsButton = new javax.swing.JButton();
        lblLastUpdatedValue = new javax.swing.JLabel();
        lastUpdateText = new javax.swing.JTextField();
        expiredCertButton = new javax.swing.JButton();
        firstCarButton = new javax.swing.JButton();
        deleteDetailsButton = new javax.swing.JButton();
        allCarsButton = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        appBox = new javax.swing.JComboBox<>();
        lblManufacturerFilter = new javax.swing.JLabel();
        lblUsedByApp = new javax.swing.JLabel();
        madeByBox = new javax.swing.JComboBox<>();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        lblCountAvlCars = new javax.swing.JLabel();
        lblCountUnAvlCars = new javax.swing.JLabel();
        txtCountAvlCars = new javax.swing.JTextField();
        txtCountUnAvlCars = new javax.swing.JTextField();
        availStatusButton = new javax.swing.JButton();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        manuYearButton = new javax.swing.JButton();
        lblManufacturedYearFilter = new javax.swing.JLabel();
        manuYearFilterText = new javax.swing.JTextField();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        lblManufacturedYearFilter1 = new javax.swing.JLabel();
        lblMinSeat = new javax.swing.JLabel();
        maxSeatsBox = new javax.swing.JComboBox<>();
        lblMaxSeat = new javax.swing.JLabel();
        minSeatsBox = new javax.swing.JComboBox<>();
        jLayeredPane9 = new javax.swing.JLayeredPane();
        modelFilterButton = new javax.swing.JButton();
        txtModelNumberFilter = new javax.swing.JTextField();
        lblModelNumberFilter = new javax.swing.JLabel();
        jLayeredPane10 = new javax.swing.JLayeredPane();
        cityFilterButton = new javax.swing.JButton();
        lblCityFilter = new javax.swing.JLabel();
        cityFilterText = new javax.swing.JTextField();
        jLayeredPane11 = new javax.swing.JLayeredPane();
        serialNoFilterText = new javax.swing.JTextField();
        serialNoFilterButton = new javax.swing.JButton();
        lblSerialNumberFilter = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        lblUsedBy = new javax.swing.JLabel();
        lblMaintenanceCertExpDate = new javax.swing.JLabel();
        lblManufacturedDate = new javax.swing.JLabel();
        lblSeatCapacity = new javax.swing.JLabel();
        lblCarSerialNum = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblCarManufacturer = new javax.swing.JLabel();
        availSeatsText = new javax.swing.JTextField();
        lblCarModelNum = new javax.swing.JLabel();
        serialNumText = new javax.swing.JTextField();
        lastUpdatedTextBox = new javax.swing.JTextField();
        modelNumText = new javax.swing.JTextField();
        cityText = new javax.swing.JTextField();
        lblLastUpdated = new javax.swing.JLabel();
        certExpText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        manuOnText = new javax.swing.JTextField();
        availBox = new java.awt.Checkbox();
        manuByText = new javax.swing.JTextField();
        appText = new javax.swing.JTextField();
        updateDetailsButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(214, 238, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Car Details");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblViewCarDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Model Number", "Serial Number", "Car Model", "Manufactured Date", "Seat Capacity", "Is Available", "City", "Used By App"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewCarDetails);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        viewDetailsButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        viewDetailsButton.setText("View");
        viewDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsButtonActionPerformed(evt);
            }
        });

        lblLastUpdatedValue.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblLastUpdatedValue.setText("Last Updated");

        lastUpdateText.setBackground(new java.awt.Color(204, 204, 204));
        lastUpdateText.setText("                   ");
        lastUpdateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastUpdateTextActionPerformed(evt);
            }
        });

        expiredCertButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        expiredCertButton.setText("List Expired Certificate");
        expiredCertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiredCertButtonActionPerformed(evt);
            }
        });

        firstCarButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        firstCarButton.setText("First Available Car");
        firstCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstCarButtonActionPerformed(evt);
            }
        });

        deleteDetailsButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        deleteDetailsButton.setText("Delete");
        deleteDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDetailsButtonActionPerformed(evt);
            }
        });

        allCarsButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        allCarsButton.setText("All Available Cars");
        allCarsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allCarsButtonActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(viewDetailsButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lblLastUpdatedValue, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lastUpdateText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(expiredCertButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(firstCarButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(deleteDetailsButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(allCarsButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(viewDetailsButton)
                .addGap(28, 28, 28)
                .addComponent(deleteDetailsButton)
                .addGap(18, 18, 18)
                .addComponent(firstCarButton)
                .addGap(18, 18, 18)
                .addComponent(allCarsButton)
                .addGap(18, 18, 18)
                .addComponent(lblLastUpdatedValue)
                .addGap(18, 18, 18)
                .addComponent(lastUpdateText, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(expiredCertButton)
                .addGap(26, 26, 26))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewDetailsButton)
                    .addComponent(deleteDetailsButton)
                    .addComponent(firstCarButton)
                    .addComponent(allCarsButton)
                    .addComponent(lblLastUpdatedValue)
                    .addComponent(lastUpdateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiredCertButton))
                .addContainerGap())
        );

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        appBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        appBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uber", "Lyft", "Ola", "All" }));
        appBox.setSelectedIndex(-1);
        appBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        appBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appBoxActionPerformed(evt);
            }
        });

        lblManufacturerFilter.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblManufacturerFilter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManufacturerFilter.setText("Car Model");

        lblUsedByApp.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblUsedByApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsedByApp.setText("Used By App");

        madeByBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        madeByBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acura", "Audi", "Bentley", "Cadillac", "Dodge" }));
        madeByBox.setSelectedIndex(-1);
        madeByBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        madeByBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madeByBoxActionPerformed(evt);
            }
        });

        jLayeredPane4.setLayer(appBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(lblManufacturerFilter, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(lblUsedByApp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(madeByBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManufacturerFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(madeByBox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(appBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(lblUsedByApp, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturerFilter)
                    .addComponent(lblUsedByApp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(madeByBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLayeredPane6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCountAvlCars.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblCountAvlCars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountAvlCars.setText("Available");

        lblCountUnAvlCars.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblCountUnAvlCars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountUnAvlCars.setText("Occupied");

        txtCountAvlCars.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCountAvlCars.setText("0");
        txtCountAvlCars.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtCountUnAvlCars.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCountUnAvlCars.setText("0");
        txtCountUnAvlCars.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        availStatusButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        availStatusButton.setText("Car Availability Status");
        availStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availStatusButtonActionPerformed(evt);
            }
        });

        jLayeredPane6.setLayer(lblCountAvlCars, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(lblCountUnAvlCars, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(txtCountAvlCars, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(txtCountUnAvlCars, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(availStatusButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(availStatusButton)
                .addContainerGap())
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtCountAvlCars, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCountAvlCars, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCountUnAvlCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCountUnAvlCars, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(availStatusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountAvlCars)
                    .addComponent(lblCountUnAvlCars))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCountAvlCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCountUnAvlCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        manuYearButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        manuYearButton.setText("OK");
        manuYearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuYearButtonActionPerformed(evt);
            }
        });

        lblManufacturedYearFilter.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblManufacturedYearFilter.setText("Filter by Manufactured Year");

        manuYearFilterText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLayeredPane7.setLayer(manuYearButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(lblManufacturedYearFilter, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(manuYearFilterText, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane7Layout = new javax.swing.GroupLayout(jLayeredPane7);
        jLayeredPane7.setLayout(jLayeredPane7Layout);
        jLayeredPane7Layout.setHorizontalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblManufacturedYearFilter))
                    .addGroup(jLayeredPane7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(manuYearFilterText, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane7Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(manuYearButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane7Layout.setVerticalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManufacturedYearFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manuYearFilterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manuYearButton)
                .addContainerGap())
        );

        jLayeredPane8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane8.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        lblManufacturedYearFilter1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblManufacturedYearFilter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManufacturedYearFilter1.setText("Filter by Seats Availability");

        lblMinSeat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblMinSeat.setText("Min.");

        maxSeatsBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));
        maxSeatsBox.setSelectedIndex(9);
        maxSeatsBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        maxSeatsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxSeatsBoxActionPerformed(evt);
            }
        });

        lblMaxSeat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblMaxSeat.setText("Max.");

        minSeatsBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        minSeatsBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        minSeatsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minSeatsBoxActionPerformed(evt);
            }
        });

        jLayeredPane8.setLayer(lblManufacturedYearFilter1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(lblMinSeat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(maxSeatsBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(lblMaxSeat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(minSeatsBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane8Layout = new javax.swing.GroupLayout(jLayeredPane8);
        jLayeredPane8.setLayout(jLayeredPane8Layout);
        jLayeredPane8Layout.setHorizontalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane8Layout.createSequentialGroup()
                        .addGroup(jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblManufacturedYearFilter1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                                .addComponent(lblMinSeat)
                                .addGap(81, 81, 81)
                                .addComponent(lblMaxSeat)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jLayeredPane8Layout.createSequentialGroup()
                        .addComponent(minSeatsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maxSeatsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jLayeredPane8Layout.setVerticalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManufacturedYearFilter1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinSeat)
                    .addComponent(lblMaxSeat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minSeatsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxSeatsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLayeredPane9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        modelFilterButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        modelFilterButton.setText("OK");
        modelFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelFilterButtonActionPerformed(evt);
            }
        });

        txtModelNumberFilter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblModelNumberFilter.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblModelNumberFilter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModelNumberFilter.setText("Filter by Model Number");

        jLayeredPane9.setLayer(modelFilterButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane9.setLayer(txtModelNumberFilter, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane9.setLayer(lblModelNumberFilter, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane9Layout = new javax.swing.GroupLayout(jLayeredPane9);
        jLayeredPane9.setLayout(jLayeredPane9Layout);
        jLayeredPane9Layout.setHorizontalGroup(
            jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtModelNumberFilter, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane9Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblModelNumberFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jLayeredPane9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(modelFilterButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane9Layout.setVerticalGroup(
            jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblModelNumberFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtModelNumberFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modelFilterButton)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLayeredPane10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cityFilterButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cityFilterButton.setText("OK");
        cityFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFilterButtonActionPerformed(evt);
            }
        });

        lblCityFilter.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblCityFilter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCityFilter.setText("Filter by City");

        cityFilterText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLayeredPane10.setLayer(cityFilterButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane10.setLayer(lblCityFilter, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane10.setLayer(cityFilterText, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane10Layout = new javax.swing.GroupLayout(jLayeredPane10);
        jLayeredPane10.setLayout(jLayeredPane10Layout);
        jLayeredPane10Layout.setHorizontalGroup(
            jLayeredPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cityFilterText))
                    .addComponent(lblCityFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
            .addGroup(jLayeredPane10Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(cityFilterButton)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jLayeredPane10Layout.setVerticalGroup(
            jLayeredPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCityFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cityFilterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cityFilterButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        serialNoFilterText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        serialNoFilterButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        serialNoFilterButton.setText("OK");
        serialNoFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNoFilterButtonActionPerformed(evt);
            }
        });

        lblSerialNumberFilter.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblSerialNumberFilter.setText("Filter by Serial Number");

        jLayeredPane11.setLayer(serialNoFilterText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(serialNoFilterButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(lblSerialNumberFilter, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane11Layout = new javax.swing.GroupLayout(jLayeredPane11);
        jLayeredPane11.setLayout(jLayeredPane11Layout);
        jLayeredPane11Layout.setHorizontalGroup(
            jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane11Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(serialNoFilterText, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSerialNumberFilter))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(serialNoFilterButton)
                .addGap(67, 67, 67))
        );
        jLayeredPane11Layout.setVerticalGroup(
            jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSerialNumberFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(serialNoFilterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(serialNoFilterButton)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUsedBy.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblUsedBy.setForeground(new java.awt.Color(255, 255, 255));
        lblUsedBy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsedBy.setText("Used By App");

        lblMaintenanceCertExpDate.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblMaintenanceCertExpDate.setForeground(new java.awt.Color(255, 255, 255));
        lblMaintenanceCertExpDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaintenanceCertExpDate.setText("Certificate Expire Date");

        lblManufacturedDate.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblManufacturedDate.setForeground(new java.awt.Color(255, 255, 255));
        lblManufacturedDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManufacturedDate.setText("Manufactured On");

        lblSeatCapacity.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblSeatCapacity.setForeground(new java.awt.Color(255, 255, 255));
        lblSeatCapacity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeatCapacity.setText("Number of Seats Available");

        lblCarSerialNum.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblCarSerialNum.setForeground(new java.awt.Color(255, 255, 255));
        lblCarSerialNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarSerialNum.setText("Serial Number");

        lblCity.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCity.setText("City");

        lblCarManufacturer.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblCarManufacturer.setForeground(new java.awt.Color(255, 255, 255));
        lblCarManufacturer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarManufacturer.setText("Made By");

        lblCarModelNum.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblCarModelNum.setForeground(new java.awt.Color(255, 255, 255));
        lblCarModelNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarModelNum.setText("Model Number");

        modelNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNumTextActionPerformed(evt);
            }
        });

        lblLastUpdated.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblLastUpdated.setForeground(new java.awt.Color(255, 255, 255));
        lblLastUpdated.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLastUpdated.setText("Last Updated");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Availability of Car");

        availBox.setLabel("Is Available");

        updateDetailsButton.setBackground(new java.awt.Color(51, 51, 51));
        updateDetailsButton.setForeground(new java.awt.Color(255, 255, 255));
        updateDetailsButton.setText("Update Car Details");
        updateDetailsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDetailsButtonActionPerformed(evt);
            }
        });

        jLayeredPane5.setLayer(lblUsedBy, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(lblMaintenanceCertExpDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(lblManufacturedDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(lblSeatCapacity, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(lblCarSerialNum, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(lblCity, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(lblCarManufacturer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(availSeatsText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(lblCarModelNum, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(serialNumText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(lastUpdatedTextBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(modelNumText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(cityText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(lblLastUpdated, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(certExpText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(manuOnText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(availBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(manuByText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(appText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(updateDetailsButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblMaintenanceCertExpDate)
                                .addComponent(lblLastUpdated)
                                .addComponent(jLabel2)
                                .addComponent(lblCarSerialNum)
                                .addComponent(lblCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUsedBy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblSeatCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(lblManufacturedDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCarModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarManufacturer))
                        .addGap(42, 42, 42)
                        .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modelNumText, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(serialNumText, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(manuOnText, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(availSeatsText, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(cityText, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(certExpText, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(lastUpdatedTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(availBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manuByText)
                            .addComponent(appText)))
                    .addGroup(jLayeredPane5Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(updateDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLayeredPane5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {availSeatsText, certExpText, cityText, lastUpdatedTextBox, manuOnText, modelNumText, serialNumText});

        jLayeredPane5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, lblCarManufacturer, lblCarModelNum, lblCarSerialNum, lblCity, lblLastUpdated, lblMaintenanceCertExpDate, lblManufacturedDate, lblSeatCapacity, lblUsedBy});

        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarModelNum)
                    .addComponent(modelNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarSerialNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manuByText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarManufacturer))
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manuOnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManufacturedDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availSeatsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeatCapacity))
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsedBy)
                    .addComponent(appText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaintenanceCertExpDate)
                    .addComponent(certExpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastUpdated)
                    .addComponent(lastUpdatedTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(availBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateDetailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        jLayeredPane5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {availSeatsText, certExpText, cityText, lastUpdatedTextBox, manuOnText, modelNumText, serialNumText});

        jLayeredPane5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, lblCarManufacturer, lblCarModelNum, lblCarSerialNum, lblCity, lblLastUpdated, lblMaintenanceCertExpDate, lblManufacturedDate, lblSeatCapacity, lblUsedBy});

        jDesktopPane1.setLayer(jLayeredPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLayeredPane7)
                            .addComponent(jLayeredPane9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLayeredPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLayeredPane6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLayeredPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane6)
                    .addComponent(jLayeredPane10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLayeredPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modelNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNumTextActionPerformed

    private void deleteDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDetailsButtonActionPerformed
        int selectedRowIndex = tblViewCarDetails.getSelectedRow();
        
        if(selectedRowIndex < 0) {  
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblViewCarDetails.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex, 0);
        
        carFleetDetails.removeCar(selectedCar);
        JOptionPane.showMessageDialog(this, "Car deleted");
        
        populateTable();
    }//GEN-LAST:event_deleteDetailsButtonActionPerformed

    private void viewDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsButtonActionPerformed
        int selectedRowIndex = tblViewCarDetails.getSelectedRow();
        
        if(selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view details");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblViewCarDetails.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex, 0);
        
        modelNumText.setText(String.valueOf(selectedCar.getModelNumber()));
        serialNumText.setText(String.valueOf(selectedCar.getSerialNumber()));
        manuByText.setText(selectedCar.getManufacturer());
        manuOnText.setText(String.valueOf(selectedCar.getManufacturedDate()));
        availSeatsText.setText(String.valueOf(selectedCar.getSeatCapacity()));
        appText.setText(selectedCar.getUsedByApp());
        cityText.setText(selectedCar.getCity());
        certExpText.setText(String.valueOf(selectedCar.getMaintenanceCertExpDate()));
        lastUpdatedTextBox.setText(String.valueOf(selectedCar.getLastUpdated()));
        availBox.setState(selectedCar.isIsAvailable());
    }//GEN-LAST:event_viewDetailsButtonActionPerformed

    private void allCarsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allCarsButtonActionPerformed

        String isAvailable = "true";
        populateTableAvailable(isAvailable);
        
    }//GEN-LAST:event_allCarsButtonActionPerformed

    private void madeByBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madeByBoxActionPerformed
        populateTable();
    }//GEN-LAST:event_madeByBoxActionPerformed

    private void firstCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstCarButtonActionPerformed
        String isAvailable = "true";
        populateTableFirstAvailable();
    }//GEN-LAST:event_firstCarButtonActionPerformed

    private void availStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availStatusButtonActionPerformed
        int totalCarAvl = 0;
        int countCarAvl = 0;
        int countUnAvlCar = 0;
        for(Car c: carFleetDetails.getCarFleetDetails()) {
                totalCarAvl++;    
            if (c.isIsAvailable() == true) {
                countCarAvl++;
            }
        }
        countUnAvlCar = totalCarAvl - countCarAvl;
        txtCountAvlCars.setText(String.valueOf(countCarAvl));
        txtCountUnAvlCars.setText(String.valueOf(countUnAvlCar));
    }//GEN-LAST:event_availStatusButtonActionPerformed

    private void manuYearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuYearButtonActionPerformed

        populateTableManufacturedYear();
    }//GEN-LAST:event_manuYearButtonActionPerformed

    private void minSeatsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minSeatsBoxActionPerformed

        Object countMinCapacity = minSeatsBox.getSelectedItem();
        int countMinCapacityInt = Integer.parseInt(countMinCapacity.toString());
        maxSeatsBox.removeAllItems();
        for (int i=countMinCapacityInt; i<=10 ; i++) {
            String newcountMinCapacityInt = String.valueOf(i + 1);
            maxSeatsBox.addItem(newcountMinCapacityInt);
        }
        populateSeatCapacityFilterTable();
    }//GEN-LAST:event_minSeatsBoxActionPerformed

    private void maxSeatsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxSeatsBoxActionPerformed

        populateSeatCapacityFilterTable();
    }//GEN-LAST:event_maxSeatsBoxActionPerformed

    private void serialNoFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNoFilterButtonActionPerformed
        populateTableSerialNumberFilter();
    }//GEN-LAST:event_serialNoFilterButtonActionPerformed

    private void modelFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelFilterButtonActionPerformed
        populateTableModelNumberFilter();
    }//GEN-LAST:event_modelFilterButtonActionPerformed

    private void appBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appBoxActionPerformed
        populateTableUsedByApp();
    }//GEN-LAST:event_appBoxActionPerformed

    private void lastUpdateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastUpdateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastUpdateTextActionPerformed

    private void cityFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFilterButtonActionPerformed
        populateTableCityFilter();
    }//GEN-LAST:event_cityFilterButtonActionPerformed

    private void expiredCertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiredCertButtonActionPerformed
        populateTableExpiredCertFilter();
    }//GEN-LAST:event_expiredCertButtonActionPerformed

    private void updateDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDetailsButtonActionPerformed
       int SerialNumber = Integer.parseInt(serialNumText.getText());
       for(Car c: carFleetDetails.getCarFleetDetails()) {
            if(!serialNumText.getText().isEmpty() && c.getSerialNumber() == SerialNumber) {
                LocalDate todaysDate = LocalDate.now();
                boolean available = availBox.getState();
                DateTimeFormatter dformatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                LocalDate localDate = LocalDate.parse(manuOnText.getText(), dformatter);
                LocalDate manufacturedDate = localDate;
                LocalDate localDateCerExp = LocalDate.parse(certExpText.getText(), dformatter);
                Object viewUsedByApp = appBox.getSelectedItem();
                String usedBy = viewUsedByApp.toString();
                Object viewManufacturedBy = madeByBox.getSelectedItem();
                String manufacturedBy = viewManufacturedBy.toString();
                c.setModelNumber(Integer.parseInt(modelNumText.getText()));
                c.setManufacturedDate(manufacturedDate);
                c.setSeatCapacity(Integer.parseInt(availSeatsText.getText()));
                c.setCity(cityText.getText());
                c.setUsedByApp(usedBy);
                c.setManufacturer(manufacturedBy);
                c.setMaintenanceCertExpDate(localDateCerExp);
                c.setLastUpdated(todaysDate);
                c.setIsAvailable(available);
            }
        }
        populateTable();
    }//GEN-LAST:event_updateDetailsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allCarsButton;
    private javax.swing.JComboBox<String> appBox;
    private javax.swing.JTextField appText;
    private java.awt.Checkbox availBox;
    private javax.swing.JTextField availSeatsText;
    private javax.swing.JButton availStatusButton;
    private javax.swing.JTextField certExpText;
    private javax.swing.JButton cityFilterButton;
    private javax.swing.JTextField cityFilterText;
    private javax.swing.JTextField cityText;
    private javax.swing.JButton deleteDetailsButton;
    private javax.swing.JButton expiredCertButton;
    private javax.swing.JButton firstCarButton;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane10;
    private javax.swing.JLayeredPane jLayeredPane11;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JLayeredPane jLayeredPane9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastUpdateText;
    private javax.swing.JTextField lastUpdatedTextBox;
    private javax.swing.JLabel lblCarManufacturer;
    private javax.swing.JLabel lblCarModelNum;
    private javax.swing.JLabel lblCarSerialNum;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCityFilter;
    private javax.swing.JLabel lblCountAvlCars;
    private javax.swing.JLabel lblCountUnAvlCars;
    private javax.swing.JLabel lblLastUpdated;
    private javax.swing.JLabel lblLastUpdatedValue;
    private javax.swing.JLabel lblMaintenanceCertExpDate;
    private javax.swing.JLabel lblManufacturedDate;
    private javax.swing.JLabel lblManufacturedYearFilter;
    private javax.swing.JLabel lblManufacturedYearFilter1;
    private javax.swing.JLabel lblManufacturerFilter;
    private javax.swing.JLabel lblMaxSeat;
    private javax.swing.JLabel lblMinSeat;
    private javax.swing.JLabel lblModelNumberFilter;
    private javax.swing.JLabel lblSeatCapacity;
    private javax.swing.JLabel lblSerialNumberFilter;
    private javax.swing.JLabel lblUsedBy;
    private javax.swing.JLabel lblUsedByApp;
    private javax.swing.JComboBox<String> madeByBox;
    private javax.swing.JTextField manuByText;
    private javax.swing.JTextField manuOnText;
    private javax.swing.JButton manuYearButton;
    private javax.swing.JTextField manuYearFilterText;
    private javax.swing.JComboBox<String> maxSeatsBox;
    private javax.swing.JComboBox<String> minSeatsBox;
    private javax.swing.JButton modelFilterButton;
    private javax.swing.JTextField modelNumText;
    private javax.swing.JButton serialNoFilterButton;
    private javax.swing.JTextField serialNoFilterText;
    private javax.swing.JTextField serialNumText;
    private javax.swing.JTable tblViewCarDetails;
    private javax.swing.JTextField txtCountAvlCars;
    private javax.swing.JTextField txtCountUnAvlCars;
    private javax.swing.JTextField txtModelNumberFilter;
    private javax.swing.JButton updateDetailsButton;
    private javax.swing.JButton viewDetailsButton;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblViewCarDetails.getModel();
        model.setRowCount(0);
        
        Object selectedManufacturer = madeByBox.getSelectedItem();
        ArrayList<LocalDate> allUpdates = new ArrayList<LocalDate>();
        
        for(Car c: carFleetDetails.getCarFleetDetails()) {
            if (selectedManufacturer != null && selectedManufacturer.equals(c.getManufacturer())) {
            Object [] row = new Object[8];
            row[0] = c;
            row[1] = c.getSerialNumber();
            row[2] = c.getManufacturer();
            row[3] = c.getManufacturedDate();
            row[4] = c.getSeatCapacity();
            row[5] = c.isIsAvailable();
            row[6] = c.getCity();
            row[7] = c.getUsedByApp();
            
            model.addRow(row); 
            } else if(selectedManufacturer == null || selectedManufacturer == "All") {
                Object [] row = new Object[8];
            row[0] = c;
            row[1] = c.getSerialNumber();
            row[2] = c.getManufacturer();
            row[3] = c.getManufacturedDate();
            row[4] = c.getSeatCapacity();
            row[5] = c.isIsAvailable();
            row[6] = c.getCity();
            row[7] = c.getUsedByApp();
            
            model.addRow(row); 
            }
        }
        for(Car c: carFleetDetails.getCarFleetDetails()) {
            allUpdates.add(c.getLastUpdated());
        }
        
        if (!allUpdates.isEmpty()) {
            System.out.println("inside");
                   LocalDate maxDate = allUpdates.get(0); 

        for (int i = 1; i < allUpdates.size()-1; i++) { 
                if (allUpdates.get(i).isAfter(maxDate)) { 
                        maxDate = allUpdates.get(i); 
                } 
        }
        lastUpdateText.setText(String.valueOf(maxDate)); 
        }
        
    }
    
    private void populateTableUsedByApp() {
        DefaultTableModel model = (DefaultTableModel) tblViewCarDetails.getModel();
        model.setRowCount(0);
        
        Object selectedUsedByApp = appBox.getSelectedItem();
        
        for(Car c: carFleetDetails.getCarFleetDetails()) {
            if (selectedUsedByApp != null && selectedUsedByApp.equals(c.getUsedByApp())) {
            Object [] row = new Object[8];
            row[0] = c;
            row[1] = c.getSerialNumber();
            row[2] = c.getManufacturer();
            row[3] = c.getManufacturedDate();
            row[4] = c.getSeatCapacity();
            row[5] = c.isIsAvailable();
            row[6] = c.getCity();
            row[7] = c.getUsedByApp();
            
            model.addRow(row); 
            } else if(selectedUsedByApp == null || selectedUsedByApp == "All") {
                Object [] row = new Object[8];
            row[0] = c;
            row[1] = c.getSerialNumber();
            row[2] = c.getManufacturer();
            row[3] = c.getManufacturedDate();
            row[4] = c.getSeatCapacity();
            row[5] = c.isIsAvailable();
            row[6] = c.getCity();
            row[7] = c.getUsedByApp();
            
            model.addRow(row); 
            }
        }
        
    }
    
    private void populateTableAvailable(String isAvailable) {
        DefaultTableModel model = (DefaultTableModel) tblViewCarDetails.getModel();
        model.setRowCount(0);
        
        for(Car c: carFleetDetails.getCarFleetDetails()) {
            
            if(c.isIsAvailable() == true) {
                Object [] row = new Object[8];
                row[0] = c;
                row[1] = c.getSerialNumber();
                row[2] = c.getManufacturer();
                row[3] = c.getManufacturedDate();
                row[4] = c.getSeatCapacity();
                row[5] = c.isIsAvailable();
                row[6] = c.getCity();
                row[7] = c.getUsedByApp();

                model.addRow(row);
            }
        }
        
    }
    
    private void populateTableFirstAvailable() {
        DefaultTableModel model = (DefaultTableModel) tblViewCarDetails.getModel();
        model.setRowCount(0);
        
        for(Car c: carFleetDetails.getCarFleetDetails()) {
            
            if(c.isIsAvailable() == true) {
                Object [] row = new Object[8];
                row[0] = c;
                row[1] = c.getSerialNumber();
                row[2] = c.getManufacturer();
                row[3] = c.getManufacturedDate();
                row[4] = c.getSeatCapacity();
                row[5] = c.isIsAvailable();
                row[6] = c.getCity();
                row[7] = c.getUsedByApp();
                
                if (model.getRowCount() == 0) {
                    model.addRow(row);
                }
            }
        }
        
    }

    private void populateTableManufacturedYear() {
        DefaultTableModel model = (DefaultTableModel) tblViewCarDetails.getModel();
        model.setRowCount(0);
        int manufacturedYear = Integer.parseInt(manuYearFilterText.getText());
        
        for(Car c: carFleetDetails.getCarFleetDetails()) {
            int manuYear = c.getManufacturedDate().getYear();
            
            if(manuYear == manufacturedYear) {
                Object [] row = new Object[8];
                row[0] = c;
                row[1] = c.getSerialNumber();
                row[2] = c.getManufacturer();
                row[3] = c.getManufacturedDate();
                row[4] = c.getSeatCapacity();
                row[5] = c.isIsAvailable();
                row[6] = c.getCity();
                row[7] = c.getUsedByApp();

                model.addRow(row);
            }
        }
    }

    private void populateSeatCapacityFilterTable() {
        DefaultTableModel model = (DefaultTableModel) tblViewCarDetails.getModel();
        model.setRowCount(0);
        
        Object selectedMinCapacity = minSeatsBox.getSelectedItem();
        Object selectedMaxCapacity = maxSeatsBox.getSelectedItem();
        
        for(Car c: carFleetDetails.getCarFleetDetails()) {
            int countMinCapacityInt = Integer.parseInt(selectedMinCapacity.toString());
            int countMaxCapacityInt = 11;
            if(maxSeatsBox.getSelectedItem() != null) {
               countMaxCapacityInt = Integer.parseInt(selectedMaxCapacity.toString()); 
            }
            if (c.getSeatCapacity() <= countMaxCapacityInt && c.getSeatCapacity() >= countMinCapacityInt) {
            Object [] row = new Object[8];
            row[0] = c;
            row[1] = c.getSerialNumber();
            row[2] = c.getManufacturer();
            row[3] = c.getManufacturedDate();
            row[4] = c.getSeatCapacity();
            row[5] = c.isIsAvailable();
            row[6] = c.getCity();
            row[7] = c.getUsedByApp();
            
            model.addRow(row); 
            } 
        }
        
    }

    private void populateTableSerialNumberFilter() {
        DefaultTableModel model = (DefaultTableModel) tblViewCarDetails.getModel();
        model.setRowCount(0);
        int serialNumber = Integer.parseInt(serialNoFilterText.getText());
        
        for(Car c: carFleetDetails.getCarFleetDetails()) {
            int seriNum = c.getSerialNumber();
            
            if(seriNum == serialNumber) {
                Object [] row = new Object[8];
                row[0] = c;
                row[1] = c.getSerialNumber();
                row[2] = c.getManufacturer();
                row[3] = c.getManufacturedDate();
                row[4] = c.getSeatCapacity();
                row[5] = c.isIsAvailable();
                row[6] = c.getCity();
                row[7] = c.getUsedByApp();

                model.addRow(row);
            }
        }
    }
    
    private void populateTableModelNumberFilter() {
        DefaultTableModel model = (DefaultTableModel) tblViewCarDetails.getModel();
        model.setRowCount(0);
        int modelNumber = Integer.parseInt(txtModelNumberFilter.getText());
        
        for(Car c: carFleetDetails.getCarFleetDetails()) {
            int modelNum = c.getModelNumber();
            
            if(modelNum == modelNumber) {
                Object [] row = new Object[8];
                row[0] = c;
                row[1] = c.getSerialNumber();
                row[2] = c.getManufacturer();
                row[3] = c.getManufacturedDate();
                row[4] = c.getSeatCapacity();
                row[5] = c.isIsAvailable();
                row[6] = c.getCity();
                row[7] = c.getUsedByApp();

                model.addRow(row);
            }
        }
    }

    private void populateTableCityFilter() {
        DefaultTableModel model = (DefaultTableModel) tblViewCarDetails.getModel();
        model.setRowCount(0);
        String typeCity = cityFilterText.getText();
        
        for(Car c: carFleetDetails.getCarFleetDetails()) {
            String city = c.getCity();
            
            if(city == typeCity) {
                Object [] row = new Object[8];
                row[0] = c;
                row[1] = c.getSerialNumber();
                row[2] = c.getManufacturer();
                row[3] = c.getManufacturedDate();
                row[4] = c.getSeatCapacity();
                row[5] = c.isIsAvailable();
                row[6] = c.getCity();
                row[7] = c.getUsedByApp();

                model.addRow(row);
            }
        }
    }

    private void populateTableExpiredCertFilter() {
        DefaultTableModel model = (DefaultTableModel) tblViewCarDetails.getModel();
        model.setRowCount(0);
        LocalDate lt = LocalDate.now();
        
        for(Car c: carFleetDetails.getCarFleetDetails()) {
            LocalDate expiry = c.getMaintenanceCertExpDate();
            
            if(expiry.isBefore(lt)) {
                Object [] row = new Object[8];
                row[0] = c;
                row[1] = c.getSerialNumber();
                row[2] = c.getManufacturer();
                row[3] = c.getManufacturedDate();
                row[4] = c.getSeatCapacity();
                row[5] = c.isIsAvailable();
                row[6] = c.getCity();
                row[7] = c.getUsedByApp();

                model.addRow(row);
            }
        }
    }
}
